# Generated by Django 4.1.5 on 2023-01-18 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_create_model_film'),
    ]

    operations = [
        migrations.CreateModel(
            name='Viewer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.film')),
            ],
        ),
    ]
