# Generated by Django 4.1.5 on 2023-01-18 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_create_model_viewer'),
    ]

    operations = [
        migrations.CreateModel(
            name='RatingViews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('views', models.IntegerField(max_length=100)),
            ],
        ),
    ]
