# Generated by Django 4.1.5 on 2023-01-17 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RemontAvto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remont', models.CharField(max_length=200, verbose_name='Ремонт')),
                ('vid_remonta', models.CharField(choices=[('1', 'Ремонт подвески'), ('2', 'Ремонт двигателя'), ('3', 'Ремонт выхлопной системы'), ('4', 'Ремонт рулевого управления'), ('5', 'Ремонт системы охлаждения'), ('6', 'Ремонт тормозной системы'), ('7', 'Ремонт электрооборудования'), ('8', 'Ремонт МКПП'), ('9', 'Ремонт AКПП')], default='1', max_length=200, verbose_name='Вид ремонта')),
                ('repair_description_avto', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Вид ремонта',
                'verbose_name_plural': 'Виды ремонта',
            },
        ),
    ]
